# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-01 11:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=256)),
                ('asset_tag', models.CharField(max_length=32)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('recovery_key', models.TextField()),
                ('binary_blob', models.TextField()),
                ('binary_blob_data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='encrypteddisk',
            name='encryption_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.EncryptionType', verbose_name='System Type'),
        ),
        migrations.AddField(
            model_name='encrypteddisk',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
