# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-01 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0002_encrypteddisk_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encrypteddisk',
            old_name='binary_blob',
            new_name='legacy_binary_blob',
        ),
        migrations.RenameField(
            model_name='encrypteddisk',
            old_name='binary_blob_data',
            new_name='legacy_binary_blob_data',
        ),
    ]
