# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-01 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0003_auto_20190501_0439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encrypteddisk',
            old_name='file_size',
            new_name='legacy_file_size',
        ),
    ]
