# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-01 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0004_auto_20190501_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypteddisk',
            name='file_data',
            field=models.BinaryField(null=True),
        ),
    ]
