# Generated by Django 2.2 on 2019-05-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0005_encrypteddisk_file_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encrypteddisk',
            old_name='binary_blob',
            new_name='legacy_binary_blob',
        ),
        migrations.AddField(
            model_name='encrypteddisk',
            name='legacy_binary_blob_data',
            field=models.CharField(max_length=128, null=True),
        ),
        #migrations.RenameField(
        #    model_name='encrypteddisk',
        #    old_name='binary_blob_data',
        #    new_name='legacy_binary_blob_data',
        #),
    ]
