# Generated by Django 2.2 on 2019-05-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0006_auto_20190502_0548'),
    ]

    operations = [
    ]
