# Generated by Django 2.2 on 2019-05-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0007_remove_encrypteddisk_binary_blob_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='encrypteddisk',
            name='file_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
