# Generated by Django 2.2 on 2019-05-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0008_auto_20190502_0834'),
    ]

    operations = [
        #migrations.RemoveField(
        #    model_name='encrypteddisk',
        #    name='binary_blob_data',
        #),
        migrations.AlterField(
            model_name='encrypteddisk',
            name='file_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encrypteddisk',
            name='legacy_binary_blob',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encrypteddisk',
            name='legacy_binary_blob_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
